spring:
  jmx:
    enabled: true
kafka:
  bootstrap-servers: broker:29092
  chuck-client-id: chuck-producer
  ticket-client-id: ticket-producer
  chuck-topic: chuck-spring-topic
  ticket-topic: tickets-spring-topic
  schema-registry-url: http://schema-registry:8081
